# services:
#   app:
#     build: .
#     # Comando para mantener el contenedor corriendo en segundo plano
#     command: tail -f /dev/null
#     ports:
#       - '3000:3000'
#     volumes:
#       - ./projects:/usr/src/app/projects
#     working_dir: /usr/src/app

services:
  app:
    build: .
    command: tail -f /dev/null
    ports:
      - '3000:3000'
    volumes:
      - ./projects:/usr/src/app/projects
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=contraseña
      - MYSQL_DATABASE=movies-database
      - MYSQL_USER=david
      - MYSQL_PASSWORD=contraseña
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
